"""
Phase 2: HAPS Battery Model with Critical Fixes

CRITICAL FIX #3: HAPS Solar Power is NOT Weather-Dependent
===========================================================
WRONG:
    solar_irradiance_lstm_forecast = [600, 500, 100, 50, ...]  # From LSTM
    battery_drain_rate = compute_battery_drain(solar_forecast, user_load)
    # PROBLEM: Assumes clouds above HAPS at 20 km altitude

CORRECT (This Implementation):
    HAPS at 20 km altitude is in the STRATOSPHERE, above ~99% of clouds.
    Solar input follows DIURNAL CYCLE (sunrise/sunset at platforms).
    Solar is INDEPENDENT of ground-level rainfall.
    Feeder link rain attenuation affects LINK CAPACITY, not platform battery.

Why This Matters:
    - Ground rainfall does NOT affect HAPS solar panels
    - Spurious coupling creates backwards learning (rain → lower battery)
    - Correct model: battery from solar(time_of_day), not weather
    - Feeder link rain affects SINR/capacity (separate model)
"""

import numpy as np
from typing import Tuple


class HAPSBatteryModel:
    """HAPS battery model with correct solar input from diurnal cycle."""

    def __init__(self, battery_capacity_wh=1000.0, panel_area_m2=20.0,
                 panel_efficiency=0.20):
        """Initialize HAPS battery parameters.

        Args:
            battery_capacity_wh: Total battery capacity (Wh)
            panel_area_m2: Solar panel area (m²)
            panel_efficiency: Panel efficiency (0.0-1.0)
        """
        self.battery_capacity = battery_capacity_wh  # Wh
        self.panel_area = panel_area_m2  # m²
        self.panel_efficiency = panel_efficiency  # 20% typical

    def solar_irradiance_diurnal(self, hour_of_day: float) -> float:
        """Compute solar irradiance based on DIURNAL cycle.

        CRITICAL: This depends on TIME-OF-DAY only, not weather.
        HAPS at 20 km is in stratosphere above clouds.

        Model: Cosine wave from sunrise (~6am) to sunset (~6pm)
        P_solar(t) = 600 · max(0, cos(π(t - 12) / 12)) W/m²

        Args:
            hour_of_day: Hour in range [0, 24)

        Returns:
            Solar irradiance in W/m²
        """
        # Nominal peak irradiance at equator, mid-altitude stratosphere
        peak_irradiance = 600.0  # W/m²

        # Sunrise at 6 AM, sunset at 6 PM (12-hour daylight)
        sunrise_hour = 6.0
        sunset_hour = 18.0

        if hour_of_day < sunrise_hour or hour_of_day > sunset_hour:
            return 0.0  # Night

        # Cosine wave centered at noon (12:00)
        # At t=12, cos(0)=1 → peak; at t=6 or t=18, cos(±π)=-0.5 → low
        phase = np.pi * (hour_of_day - 12.0) / 12.0
        irradiance = peak_irradiance * np.maximum(0.0, np.cos(phase))

        return irradiance

    def solar_power_generated(self, hour_of_day: float) -> float:
        """Compute solar power generated by HAPS panels.

        P_solar = Irradiance × Panel Area × Efficiency

        Args:
            hour_of_day: Hour in range [0, 24)

        Returns:
            Solar power in Watts
        """
        irradiance = self.solar_irradiance_diurnal(hour_of_day)
        power = irradiance * self.panel_area * self.panel_efficiency
        return power

    def update_battery_soc(self, current_soc_percent: float, hour_of_day: float,
                          user_load_watts: float,
                          feeder_link_power_base: float = 500.0,
                          platform_power: float = 200.0) -> Tuple[float, dict]:
        """Update HAPS battery state of charge for one hour.

        Energy balance: ΔE = P_solar - (P_feeder + P_platform + P_user)

        Args:
            current_soc_percent: Current battery SoC (0-100%)
            hour_of_day: Hour in range [0, 24)
            user_load_watts: Assigned user load (Watts)
            feeder_link_power_base: Baseline feeder link power (Watts)
            platform_power: Platform payload + guidance power (Watts)

        Returns:
            Tuple of (new_soc_percent, debug_dict)
        """
        # Input power: DIURNAL SOLAR ONLY (not weather-dependent)
        p_solar = self.solar_power_generated(hour_of_day)

        # Output power: Fixed + user load
        # NOTE: Feeder link rain affects LINK CAPACITY (SINR), not power consumption
        p_load = feeder_link_power_base + platform_power + user_load_watts

        # Net power (Watts)
        p_net = p_solar - p_load

        # Energy change over 1 hour (Wh)
        energy_change_wh = p_net * 1.0  # 1 hour

        # New SoC
        new_soc_percent = current_soc_percent + (energy_change_wh / self.battery_capacity)
        new_soc_percent = np.clip(new_soc_percent, 0.0, 100.0)

        debug = {
            "hour_of_day": hour_of_day,
            "solar_irradiance_w_m2": self.solar_irradiance_diurnal(hour_of_day),
            "p_solar_w": p_solar,
            "p_feeder_w": feeder_link_power_base,
            "p_platform_w": platform_power,
            "p_user_w": user_load_watts,
            "p_load_total_w": p_load,
            "p_net_w": p_net,
            "energy_change_wh": energy_change_wh,
            "soc_before": current_soc_percent,
            "soc_after": new_soc_percent
        }

        return new_soc_percent, debug


def feeder_link_rain_effect_on_capacity(rain_mm_h: float) -> dict:
    """Compute feeder link attenuation due to rain (affects CAPACITY, not battery).

    NOTE: This is SEPARATE from battery model.
    Rain affects link SINR/capacity, not platform power consumption.

    Args:
        rain_mm_h: Rainfall rate (mm/h)

    Returns:
        Dict with attenuation and resulting capacity
    """
    # ITU-R P.838 rain model at 38 GHz
    # A_rain = k * R^α, where k=0.0315, α=0.921 for 38 GHz
    k = 0.0315
    alpha = 0.921

    rain_attenuation_db = k * (rain_mm_h ** alpha)

    # For 102 km slant path with reduction factor r(θ) ≈ 0.65
    slant_path_km = 102.0
    reduction_factor = 0.65
    effective_path_km = slant_path_km * reduction_factor

    total_rain_loss_db = rain_attenuation_db * effective_path_km

    return {
        "rain_mm_h": rain_mm_h,
        "rain_attenuation_db_per_km": rain_attenuation_db,
        "effective_path_km": effective_path_km,
        "total_rain_loss_db": total_rain_loss_db
    }


# ===== Unit Tests =====

def test_solar_at_midnight():
    """Test: Solar power is zero at midnight"""
    battery = HAPSBatteryModel()
    solar_power = battery.solar_power_generated(hour_of_day=0.0)  # Midnight
    assert solar_power == 0.0, f"Expected 0 W at midnight, got {solar_power} W"
    print("[PASS] test_solar_at_midnight")


def test_solar_at_noon():
    """Test: Solar power peaks at noon"""
    battery = HAPSBatteryModel()
    solar_power = battery.solar_power_generated(hour_of_day=12.0)  # Noon

    # Should be peak: 600 W/m² × 20 m² × 0.2 = 2400 W
    expected = 600.0 * 20.0 * 0.20
    assert np.isclose(solar_power, expected), f"Expected {expected} W, got {solar_power} W"
    print("[PASS] test_solar_at_noon")


def test_battery_drain_at_night():
    """Test: Battery drains at night (no solar input)"""
    battery = HAPSBatteryModel()

    # At midnight with user load: should lose energy
    soc_before = 100.0
    soc_after, debug = battery.update_battery_soc(
        current_soc_percent=soc_before,
        hour_of_day=0.0,  # Midnight (no solar)
        user_load_watts=100.0
    )

    assert soc_after < soc_before, "Battery should drain at night"
    assert debug['p_solar_w'] == 0.0, "Solar power should be zero at night"
    print(f"[PASS] test_battery_drain_at_night (SoC: {soc_before}% -> {soc_after:.1f}%)")


def test_battery_stable_at_noon_with_load():
    """Test: Battery approximately stable at noon if load < solar"""
    battery = HAPSBatteryModel()

    # At noon with moderate load: solar should mostly offset load
    soc_before = 50.0
    user_load = 100.0  # 100 W user load

    soc_after, debug = battery.update_battery_soc(
        current_soc_percent=soc_before,
        hour_of_day=12.0,  # Noon (peak solar)
        user_load_watts=user_load
    )

    # At noon: P_solar ≈ 2400 W
    # P_load = 500 + 200 + 100 = 800 W
    # P_net ≈ 1600 W → battery charges
    assert soc_after > soc_before, "Battery should charge at noon with positive P_net"
    print(f"[PASS] test_battery_stable_at_noon_with_load (SoC: {soc_before}% -> {soc_after:.1f}%)")


if __name__ == "__main__":
    print("Running verification tests for Battery Model (FIX #3)...\n")

    test_solar_at_midnight()
    test_solar_at_noon()
    test_battery_drain_at_night()
    test_battery_stable_at_noon_with_load()

    print("\n[PASS] All tests passed! Solar input correctly depends on TIME only, not weather.\n")

    # Example: Full 24-hour battery profile
    print("Example: 24-hour battery profile with diurnal solar cycle")
    battery = HAPSBatteryModel()

    soc = 100.0
    for hour in range(24):
        soc, debug = battery.update_battery_soc(
            current_soc_percent=soc,
            hour_of_day=float(hour),
            user_load_watts=50.0  # Moderate user load
        )
        if hour % 6 == 0:  # Print every 6 hours
            print(f"  Hour {hour:2d}: P_solar={debug['p_solar_w']:7.1f} W, "
                  f"P_load={debug['p_load_total_w']:7.1f} W, "
                  f"SoC={soc:6.1f}%")

    print("\n[OK] Battery charges during day (P_solar high), drains at night (P_solar=0)")
