#!/usr/bin/env bash
# WSL-optimized script to generate all figures, tables, and models
# Automatically activates quantum_env virtual environment

set -u  # Exit on undefined variables, but continue on command failures

# Setup paths (script is now in src/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"  # src/
SRC_DIR="$SCRIPT_DIR"                                       # src/
ROOT_DIR="$(dirname "$SRC_DIR")"                           # root/
OUTPUT_DIR="$SRC_DIR/output"
GENERATORS_DIR="$SRC_DIR/generators"
MODELS_DIR="$SRC_DIR/models"
DATA_DIR="$SRC_DIR/data"
PLOTS_DIR="$SRC_DIR/plots"

# Destination directories (at project root)
FIGURES_DIR="$ROOT_DIR/figures"
TABLES_DIR="$ROOT_DIR/appendix_tables"

# Virtual environment paths
CONDA_HOME="$HOME/miniconda3"
VENV_PATH="$CONDA_HOME/envs/quantum_env"

# Export PYTHONPATH so generators can find modules
export PYTHONPATH="$SRC_DIR:${PYTHONPATH:-}"

# Counters
SUCCESS=0
FAILED=0

# Helper functions
run_script() {
  local script="$1"
  local use_venv="${2:-false}"

  if [ ! -f "$script" ]; then
    echo "    SKIP: $(basename "$script") not found"
    return 1
  fi

  echo "==> Running: $(basename "$script")"

  # Run from SRC_DIR to ensure relative imports work
  local script_rel="${script#$SRC_DIR/}"

  if [ "$use_venv" = "true" ] && [ -d "$VENV_PATH" ]; then
    # Activate virtual environment and run script
    if source "$VENV_PATH/bin/activate" 2>/dev/null && (cd "$SRC_DIR" && python "$script_rel"); then
      deactivate 2>/dev/null || true
      return 0
    else
      deactivate 2>/dev/null || true
      echo "    ERROR: $(basename "$script") failed"
      return 1
    fi
  else
    # Run without virtual environment
    if (cd "$SRC_DIR" && python "$script_rel"); then
      return 0
    else
      echo "    ERROR: $(basename "$script") failed"
      return 1
    fi
  fi
}

copy_files() {
  local src_dir="$1"
  local pattern="$2"
  local dest_dir="$3"

  mkdir -p "$dest_dir"

  find "$src_dir" -type f -iname "$pattern" ! -path "$dest_dir/*" -exec cp -n {} "$dest_dir/" \; 2>/dev/null || true
}

# Main execution
echo "========================================================================"
echo "HAPS Ground Communications - Generate All Figures and Tables (WSL)"
echo "========================================================================"

# Check for virtual environment
if [ ! -d "$VENV_PATH" ]; then
  echo "WARNING: quantum_env not found at $VENV_PATH"
  echo "  channel_model.py may fail"
  echo ""
fi

mkdir -p "$OUTPUT_DIR"

# STAGE 0: DQN Training (OPTIONAL - takes 30-120 minutes)
echo ""
echo "========================================================================"
echo "STAGE 0: DQN Training (OPTIONAL)"
echo "========================================================================"
echo ""
echo "WARNING: DQN training takes 30-120 minutes depending on hardware."
echo "To run DQN training (generates reward landscapes for Phase 2 figures):"
echo "  python train_dqn_phase2.py"
echo ""
echo "Skipping by default. Phase 2 figures will still generate but without"
echo "full DQN-based reward landscapes."
echo ""

# STAGE 1: Data Generation (FUTURE: LSTM forecasting models)
echo ""
echo "========================================================================"
echo "STAGE 1: Data Generation (Reserved for LSTM/Forecasting)"
echo "========================================================================"
echo "Currently skipped - for future LSTM time-series forecasting models"
echo "When implemented, place generators in: src/data/"
echo ""

if [ -d "$DATA_DIR" ]; then
  echo "Found data generation scripts in $DATA_DIR:"
  for script in "$DATA_DIR"/*.py; do
    [ -f "$script" ] && if run_script "$script" false; then
      ((SUCCESS++))
    else
      ((FAILED++))
    fi
  done
else
  echo "SKIP: $DATA_DIR not found (expected for future phases)"
fi

# STAGE 2: Models
echo ""
echo "========================================================================"
echo "STAGE 2: Channel and Battery Models"
echo "========================================================================"

if [ -d "$MODELS_DIR" ]; then
  # channel_model.py requires quantum_env
  if run_script "$MODELS_DIR/channel_model.py" true; then
    ((SUCCESS++))
    echo ""
    echo "    Files generated by channel_model.py:"
    if [ -d "$OUTPUT_DIR" ]; then
      find "$OUTPUT_DIR" -maxdepth 1 -type f -newer "$MODELS_DIR/channel_model.py" 2>/dev/null | sort | while read file; do
        size_kb=$(($(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null) / 1024))
        echo "      ✓ $(basename "$file") ($size_kb KB)"
      done
    fi
  else
    ((FAILED++))
  fi

  # battery_model.py can run without venv
  if run_script "$MODELS_DIR/battery_model.py" false; then
    ((SUCCESS++))
  else
    ((FAILED++))
  fi
else
  echo "Models directory not found: $MODELS_DIR"
fi

# STAGE 3: Figure and Table Generation
echo ""
echo "========================================================================"
echo "STAGE 3: Figure and Table Generation"
echo "========================================================================"

declare -a GENERATORS=(
  # *** IMPORTANT: generate_sinr_table_2d_spatial.py MUST run first (creates CSV for other generators)
  "generate_sinr_table_2d_spatial.py"

  # Generators that read the CSV above
  "generate_constellation_diagram.py"
  "generate_figure_5_multinode.py"
  "generate_sinr_heatmap.py"

  # Other generators (independent)
  "generate_figure_1b_fspl_comparison.py"
  "generate_figure7_multinode.py"
  "generate_figure_9b_scintillation_comparison.py"
  "generate_sinr_table.py"
  "generate_pathloss_table.py"
  "generate_atm_loss_tables.py"
  "generate_figures.py"
  "generate_phase2_figures.py"
  # "make_seed_figure.py"          # SKIP: requires variant_compare_log.npz
  # "replot_variants.py"           # SKIP: requires variant_compare_log.npz
)

declare -a RAN_GENERATORS=()

for gen in "${GENERATORS[@]}"; do
  if run_script "$GENERATORS_DIR/$gen" false; then
    ((SUCCESS++))
    RAN_GENERATORS+=("$gen")
  else
    ((FAILED++))
  fi
done

# STAGE 4: LaTeX Compilation
if [ -f "$PLOTS_DIR/network_diagram.tex" ]; then
  echo "==> Building LaTeX diagram: network_diagram.tex"
  if command -v pdflatex &> /dev/null; then
    (cd "$PLOTS_DIR" && pdflatex -interaction=nonstopmode network_diagram.tex >/dev/null 2>&1 || true)
    if [ -f "$PLOTS_DIR/network_diagram.pdf" ]; then
      cp -n "$PLOTS_DIR/network_diagram.pdf" "$OUTPUT_DIR/" 2>/dev/null || true
      ((SUCCESS++))
    fi
  else
    echo "    SKIP: pdflatex not available"
  fi
fi

# STAGE 4: List Generated Files
echo ""
echo "========================================================================"
echo "STAGE 4: Generated Files in src/output/"
echo "========================================================================"

if [ -d "$OUTPUT_DIR" ]; then
  find "$OUTPUT_DIR" -maxdepth 1 -type f | sort | while read file; do
    size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null)
    size_kb=$((size / 1024))
    echo "  ✓ $(basename "$file") ($size_kb KB)"
  done
else
  echo "  Output directory not found: $OUTPUT_DIR"
fi

# STAGE 5: List Generated Outputs (ready for manual copy to figures/appendix_tables)
echo ""
echo "========================================================================"
echo "STAGE 5: Generated Outputs in src/output/"
echo "========================================================================"

if [ -d "$OUTPUT_DIR" ]; then
  echo "All outputs are in: $OUTPUT_DIR"
  echo ""
  echo "To copy to figures/ and appendix_tables/ for paper compilation, run:"
  echo "  cp src/output/*.png figures/"
  echo "  cp src/output/*.csv appendix_tables/"
  echo "  cp src/output/*.tex appendix_tables/"
  echo ""
  find "$OUTPUT_DIR" -maxdepth 1 -type f | sort | while read file; do
    filename=$(basename "$file")
    ext="${filename##*.}"
    size=$(ls -lh "$file" | awk '{print $5}')
    case $ext in
      png) type="Figure" ;;
      csv|tex|txt) type="Table" ;;
      pdf) type="Diagram" ;;
      *) type="Data" ;;
    esac
    echo "  ✓ $filename ($size) [$type]"
  done
else
  echo "  Output directory not found: $OUTPUT_DIR"
fi

# Summary
echo ""
echo "========================================================================"
echo "SUMMARY"
echo "========================================================================"
echo "Successfully ran: $SUCCESS scripts"
echo "Failed: $FAILED scripts"

echo ""
echo "Generated files in: $OUTPUT_DIR"
echo "  Total: $(find "$OUTPUT_DIR" -maxdepth 1 -type f 2>/dev/null | wc -l) files"

echo ""
echo "Source scripts executed:"
for gen in "${RAN_GENERATORS[@]}"; do
  echo "  ✓ $gen"
done

echo ""
echo "Next steps:"
echo ""
echo "1. To generate full Phase 2 reward landscapes (optional, takes 30-120 min):"
echo "   python train_dqn_phase2.py"
echo ""
echo "2. Copy outputs to paper directories when ready to compile:"
echo "   cp src/output/*.png figures/"
echo "   cp src/output/*.csv src/output/*.tex appendix_tables/"
echo ""
echo "========================================================================"

exit $FAILED
